title: My CMS site
url: "http://0.0.0.0:4000/new-repo"
baseurl: "/new-repo/"
permalink: pretty
gems:
- jemoji
- jekyll-sitemap

sitemap:
	    file: "/sitemap.xml"
	    exclude:
	        - "/hello.html"
	    include_posts:
	        - "/index.html"
	    change_frequency_name: "change_frequency"
	    priority_name: "priority"